From [[https://developers.google.com/gmail/api/quickstart/ruby][Ruby Quickstart | Gmail API | Google Developers]]

* Step 1: Enable the Gmail API
Use [[https://console.developers.google.com/start/api?id=gmail][this wizard]] to create or select a project in the Google Developers Console and automatically enable the API.
Click the Go to credentials button to continue.
At the top of the page, select the OAuth consent screen tab.
Select an Email address, enter a Product name if not already set, and click the Save button.
Back on the Credentials tab, click the Add credentials button and select OAuth 2.0 client ID.
Select the application type Other and click the Create button.
Click OK to dismiss the resulting dialog.
Click the  (Download JSON) button to the right of the client ID. Move this file to your working directory and rename it client_secret.json.
* Step 2: Install the Google Client Library
Run the following command to install the library:
#+BEGIN_SRC sh
gem install "google-api-client"
#+END_SRC
See the library's [[https://developers.google.com/api-client-library/ruby/start/installation][installation page]] for the alternative installation options.
