gmailtender - Read GMail messages and dispatch some to org-capture

* Enable the Gmail API (from [[https://developers.google.com/gmail/api/quickstart/ruby][Ruby Quickstart | Gmail API | Google Developers]])
Use [[https://console.developers.google.com/start/api?id=gmail][this wizard]] to create or select a project in the Google Developers Console and automatically enable the API.
Select "Create new project" and press the "Continue" button.
Click the "Go to credentials" button to continue.
At the top of the page, select the "OAuth consent screen" tab.
Select an Email address, enter a Product name if not already set, and click the "Save" button.
Back on the "Credentials" tab, click the "Create credentials" button and select "OAuth client ID".
Select the application type "Other" and click the "Create" button.
Click "OK" to dismiss the resulting dialog.
Click the "Download JSON" button to the right of the client ID. Move this file to your working directory and rename it client_secret.json.
* Install
bundle install
* Authorize
./gmailtender.rb auth --no-log --verbose
* Scan
Usage:
  gmailtender.rb scan

Options:
      [--log], [--no-log]          # log output to ~/.log/.gmailtender.log
                                   # Default: true
  -v, [--verbose], [--no-verbose]  # increase verbosity

Scan emails
